name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    if: "!contains(github.event.head_commit.message , '[skip release]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install
      - name: Generate prisma client
        run: node_modules/.bin/prisma generate
      - name: Ls weird missing files
        run: ls -la src/library/components/
      - name: Build application
        run: pnpm run build
      - name: Build worker
        run: pnpm run build:worker
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        run: pnpx semantic-release
